### PR TITLE
Checker: Python3 Support

### PR DESCRIPTION
**Pull request by ax3l**
Related to #7: Adds Python3 support to validator script.

Pls merge ~~#6~~ first so I can rebase and run against the CI.
- [x] needs one more rebase as soon as ~~#8~~ is merged

### CODE REVIEW

**Comment by ax3l** [comment]
@RemiLehe splendid, here is the last one to finally support both python 2 & 3 :)

**Comment by RemiLehe** [comment]
Thanks for this. 
I have one question/comment : in the case where pyflakes returns an error/warning, are you sure that the command "python -m pyflakes ." in the .travis.yml file will result in an error that is detected at the level Travis CI.
My understanding is that pyflakes returns errors/warnings in the form of print messages (not raised exceptions/warnings), and therefore I think that, from the point of view of Travis CI, everything will be fine (since the script probably returns with exit status 0). 

What do you think ?

**Comment by ax3l** [comment]
yes, if it outputs something (warnings or errors) it will finish with a _non-zero_ return value. that means, the whole `before_script` block will fail which renders the test as ~~failed~~ errored :)

> (since the script probably returns with exit status 0).

nope, it's != 0 in that case :)

(Note: take care, failures in `after_script` do _not_ render a build as failed: [[1]](https://docs.travis-ci.com/user/customizing-the-build/#breaking-the-build))

**Comment by RemiLehe** [comment]
Thanks for the explanation. I'm merging it.

**Comment by RemiLehe** [comment]
Should we add the build badge in the README ?
badge

**Comment by ax3l** [comment]
oh yes, will add a PR (or push directly ;) )

**Pull request merged**
